# Generated by Django 3.2.7 on 2021-09-12 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 16, 40, 6, 50200)),
        ),
    ]
