# Generated by Django 3.2.7 on 2021-09-18 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 0, 0)),
        ),
    ]
