# Generated by Django 3.2.7 on 2021-09-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210928_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(null=True, upload_to='listings'),
        ),
    ]
